name: Push Branch Validator

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  validate-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Check Branch Prefix
        run: |
          echo "Nombre de la rama: ${{ github.ref_name }}"
          if [[ ! "${{ github.ref_name }}" =~ ^(feature/|bugfix/|hotfix/) ]]; then
            echo "❌ La rama '${{ github.ref_name }}' no sigue la convención. Debe empezar con feature/, bugfix/ o hotfix/."
            exit 1
          fi
          echo "✅ La rama '${{ github.ref_name }}' cumple con la convención."
